config/routes.rb
# == Route Map
#
#                                   Prefix Verb URI Pattern                                                                                       Controller#Action
#                       rails_health_check GET  /up(.:format)                                                                                     rails/health#show
#                              sidekiq_web      /sidekiq                                                                                          Sidekiq::Web
#                                   clicks GET  /                                                                                                 clicks#index
#                                          POST /                                                                                                 clicks#create
#                                    about GET  /about(.:format)                                                                                  about#show
#                              webmanifest GET  /manifest.v1.webmanifest(.:format)                                                                statics#manifest
#                                     root GET  /                                                                                                 clicks#index
#            rails_postmark_inbound_emails POST /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
#               rails_relay_inbound_emails POST /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
#            rails_sendgrid_inbound_emails POST /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
#      rails_mandrill_inbound_health_check GET  /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
#            rails_mandrill_inbound_emails POST /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
#             rails_mailgun_inbound_emails POST /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
#           rails_conductor_inbound_emails GET  /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
#                                          POST /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
#        new_rails_conductor_inbound_email GET  /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
#            rails_conductor_inbound_email GET  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
# new_rails_conductor_inbound_email_source GET  /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)                              rails/conductor/action_mailbox/inbound_emails/sources#new
#    rails_conductor_inbound_email_sources POST /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
#    rails_conductor_inbound_email_reroute POST /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
# rails_conductor_inbound_email_incinerate POST /rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)                            rails/conductor/action_mailbox/incinerates#create
#                       rails_service_blob GET  /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
#                 rails_service_blob_proxy GET  /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
#                                          GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
#                rails_blob_representation GET  /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
#          rails_blob_representation_proxy GET  /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
#                                          GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
#                       rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
#                update_rails_disk_service PUT  /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
#                     rails_direct_uploads POST /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create

require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', :as => :rails_health_check

  mount Sidekiq::Web => '/sidekiq'

  if Rails.configuration.x.cypress
    namespace :cypress do
      delete 'cleanup', to: 'cleanup#destroy'
    end
  end

  resources :clicks, only: %i[index create], path: '/'
  resource :about, controller: 'about', only: %i[show]

  get '/manifest.v1.webmanifest', to: 'statics#manifest', as: :webmanifest

  root to: 'clicks#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Templatus-Inertia</title>

    <meta name="description" content="Ruby on Rails template for using Inertia with Svelte">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Templatus (Inertia edition)">
    <meta name="theme-color" content="#991c1c">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="Templatus (Inertia edition)">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="msapplication-TileColor" content="#ffc40d">

    <meta name="git-commit-version" content="<%= Rails.configuration.x.git.commit_version %>">
    <meta name="git-commit-time" content="<%= Rails.configuration.x.git.commit_time %>">

    <% if Rails.configuration.x.honeybadger.api_key %>
    <meta name="honeybadger-api-key" content="<%= Rails.configuration.x.honeybadger.api_key %>">
    <% end %>

    <% if Rails.configuration.x.plausible_url %>
    <meta name="plausible-url" content= "<%= Rails.configuration.x.plausible_url %>">
    <% end %>
    <% if Rails.configuration.x.app_host %>
    <meta name="app-host" content= "<%= Rails.configuration.x.app_host %>">
    <% end %>

    <% if Rails.configuration.asset_host.present? %>
    <meta name="asset-host" content="<%= request.protocol %><%= Rails.configuration.asset_host %>">
    <% end %>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= tag :link, href: asset_path('/apple-touch-icon.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180' %>
    <%= tag :link, href: asset_path('/favicon-32x32.png'),    rel: 'icon',             type: 'image/png', sizes: '32x32' %>
    <%= tag :link, href: asset_path('/favicon-16x16.png'),    rel: 'icon',             type: 'image/png', sizes: '16x16' %>
    <%= tag :link, href: asset_path('/safari-pinned-tab.svg'),rel: 'mask-icon',        color: '#d30001' %>
    <%= tag :link, href: webmanifest_path, rel: 'manifest' %>
    <%= tag :link, href: vite_asset_path('images/logo.svg'), rel: 'preload', as: 'image' %>

    <%= vite_client_tag %>
    <%= vite_typescript_tag 'application' %>
    <%= vite_stylesheet_tag 'application' %>
  </head>

  <body>
    <noscript>
      <p>This website doesn't work without JavaScript enabled. Please enable it to continue.</p>
    </noscript>

    <%= yield %>
  </body>
</html>